# Inventaire Ansible

[control]
localhost ansible_connection=local

# Environnements
[PRD]
debian-server-1 ansible_host=192.168.1.101

[STG]
debian-server-2 ansible_host=192.168.1.102

# Rôles
[FRONT]
debian-server-1

[BACK]
debian-server-2

# Alias pour playbooks
[managed:children]
PRD
STG

[front:children]
FRONT

[database:children]
BACK
